const rhymeSections = [
  {
    title: "一东",
    lines: [
      { text: "云对雨，雪对风。", pairs: [["云", "雨"], ["雪", "风"]] },
      { text: "晚照对晴空。", pairs: [["晚照", "晴空"]] },
      { text: "来鸿对去燕。", pairs: [["来鸿", "去燕"]] },
      { text: "宿鸟对鸣虫。", pairs: [["宿鸟", "鸣虫"]] },
      { text: "三尺剑，六钧弓。", pairs: [["三尺剑", "六钧弓"]] },
    ],
  },
  {
    title: "二冬",
    lines: [
      { text: "春对夏，暮对晨。", pairs: [["春", "夏"], ["暮", "晨"]] },
      { text: "野叟对溪童。", pairs: [["野叟", "溪童"]] },
      { text: "观山对玩水。", pairs: [["观山", "玩水"]] },
      { text: "绿竹对苍松。", pairs: [["绿竹", "苍松"]] },
      { text: "燕舞对莺歌。", pairs: [["燕舞", "莺歌"]] },
    ],
  },
  {
    title: "三江",
    lines: [
      { text: "楼对阁，户对窗。", pairs: [["楼", "阁"], ["户", "窗"]] },
      { text: "巨海对长江。", pairs: [["巨海", "长江"]] },
      { text: "蓉裳对蕙帐。", pairs: [["蓉裳", "蕙帐"]] },
      { text: "玉斝对银釭。", pairs: [["玉斝", "银釭"]] },
      { text: "青布幔，碧油幢。", pairs: [["青布幔", "碧油幢"]] },
    ],
  },
  {
    title: "四支",
    lines: [
      { text: "茶对酒，赋对诗。", pairs: [["茶", "酒"], ["赋", "诗"]] },
      { text: "燕子对莺儿。", pairs: [["燕子", "莺儿"]] },
      { text: "栽花对种竹。", pairs: [["栽花", "种竹"]] },
      { text: "落絮对游丝。", pairs: [["落絮", "游丝"]] },
      { text: "柳岸对花堤。", pairs: [["柳岸", "花堤"]] },
    ],
  },
  {
    title: "五微",
    lines: [
      { text: "来对往，密对稀。", pairs: [["来", "往"], ["密", "稀"]] },
      { text: "燕舞对莺飞。", pairs: [["燕舞", "莺飞"]] },
      { text: "风清对月朗。", pairs: [["风清", "月朗"]] },
      { text: "露重对烟微。", pairs: [["露重", "烟微"]] },
      { text: "霜菊瘦，雨梅肥。", pairs: [["霜菊瘦", "雨梅肥"]] },
    ],
  },
  {
    title: "六鱼",
    lines: [
      { text: "鱼对鸟，虎对龙。", pairs: [["鱼", "鸟"], ["虎", "龙"]] },
      { text: "岸草对汀芜。", pairs: [["岸草", "汀芜"]] },
      { text: "山花对海树。", pairs: [["山花", "海树"]] },
      { text: "赤日对苍梧。", pairs: [["赤日", "苍梧"]] },
      { text: "河图对洛书。", pairs: [["河图", "洛书"]] },
    ],
  },
  {
    title: "七虞",
    lines: [
      { text: "金对玉，宝对珠。", pairs: [["金", "玉"], ["宝", "珠"]] },
      { text: "玉兔对金乌。", pairs: [["玉兔", "金乌"]] },
      { text: "孤舟对短棹。", pairs: [["孤舟", "短棹"]] },
      { text: "一雁对双凫。", pairs: [["一雁", "双凫"]] },
      { text: "横醉眼，捻吟须。", pairs: [["横醉眼", "捻吟须"]] },
    ],
  },
  {
    title: "八齐",
    lines: [
      { text: "岩对岫，涧对溪。", pairs: [["岩", "岫"], ["涧", "溪"]] },
      { text: "远岸对危堤。", pairs: [["远岸", "危堤"]] },
      { text: "鹤长对凫短。", pairs: [["鹤长", "凫短"]] },
      { text: "水雁对山鸡。", pairs: [["水雁", "山鸡"]] },
      { text: "星拱北，月流西。", pairs: [["星拱北", "月流西"]] },
    ],
  },
  {
    title: "九佳",
    lines: [
      { text: "河对海，汉对淮。", pairs: [["河", "海"], ["汉", "淮"]] },
      { text: "赤岸对朱崖。", pairs: [["赤岸", "朱崖"]] },
      { text: "鹭飞对鱼跃。", pairs: [["鹭飞", "鱼跃"]] },
      { text: "宝钿对金钗。", pairs: [["宝钿", "金钗"]] },
      { text: "鱼圉圉，鸟喈喈。", pairs: [["鱼圉圉", "鸟喈喈"]] },
    ],
  },
  {
    title: "十灰",
    lines: [
      { text: "增对损，闭对开。", pairs: [["增", "损"], ["闭", "开"]] },
      { text: "碧草对苍苔。", pairs: [["碧草", "苍苔"]] },
      { text: "书签对笔架。", pairs: [["书签", "笔架"]] },
      { text: "两曜对三台。", pairs: [["两曜", "三台"]] },
      { text: "周召虎，宋桓魋。", pairs: [["周召虎", "宋桓魋"]] },
    ],
  },
  {
    title: "十一真",
    lines: [
      { text: "邪对正，假对真。", pairs: [["邪", "正"], ["假", "真"]] },
      { text: "獬豸对麒麟。", pairs: [["獬豸", "麒麟"]] },
      { text: "韩卢对苏雁。", pairs: [["韩卢", "苏雁"]] },
      { text: "陆橘对庄椿。", pairs: [["陆橘", "庄椿"]] },
      { text: "韩五鬼，李三人。", pairs: [["韩五鬼", "李三人"]] },
    ],
  },
  {
    title: "十二文",
    lines: [
      { text: "家对国，武对文。", pairs: [["家", "国"], ["武", "文"]] },
      { text: "四辅对三军。", pairs: [["四辅", "三军"]] },
      { text: "九经对三史。", pairs: [["九经", "三史"]] },
      { text: "菊馥对兰芬。", pairs: [["菊馥", "兰芬"]] },
      { text: "歌北鄙，咏南薰。", pairs: [["歌北鄙", "咏南薰"]] },
    ],
  },
  {
    title: "十三元",
    lines: [
      { text: "幽对显，寂对喧。", pairs: [["幽", "显"], ["寂", "喧"]] },
      { text: "柳岸对桃源。", pairs: [["柳岸", "桃源"]] },
      { text: "莺朋对燕友。", pairs: [["莺朋", "燕友"]] },
      { text: "早暮对寒暄。", pairs: [["早暮", "寒暄"]] },
      { text: "鱼跃沼，鹤乘轩。", pairs: [["鱼跃沼", "鹤乘轩"]] },
    ],
  },
  {
    title: "十四寒",
    lines: [
      { text: "多对少，易对难。", pairs: [["多", "少"], ["易", "难"]] },
      { text: "虎踞对龙蟠。", pairs: [["虎踞", "龙蟠"]] },
      { text: "龙舟对凤辇。", pairs: [["龙舟", "凤辇"]] },
      { text: "白鹤对青鸾。", pairs: [["白鹤", "青鸾"]] },
      { text: "风淅淅，露漙漙。", pairs: [["风淅淅", "露漙漙"]] },
    ],
  },
  {
    title: "十五删",
    lines: [
      { text: "林对坞，岭对峦。", pairs: [["林", "坞"], ["岭", "峦"]] },
      { text: "昼永对春闲。", pairs: [["昼永", "春闲"]] },
      { text: "谋深对望重。", pairs: [["谋深", "望重"]] },
      { text: "任大对投艰。", pairs: [["任大", "投艰"]] },
      { text: "裴度宅，谢安山。", pairs: [["裴度宅", "谢安山"]] },
    ],
  },
];

const rhymePairBank = rhymeSections.flatMap((section) =>
  section.lines.flatMap((line) =>
    line.pairs.map(([left, right]) => ({
      left,
      right,
      text: line.text,
      section: section.title,
    }))
  )
);

const poems = [
  {
    title: "咏鹅",
    author: "骆宾王",
    lines: ["鹅，鹅，鹅，", "曲项向天歌。", "白毛浮绿水，", "红掌拨清波。"],
    targets: ["鹅", "天", "白", "绿", "红"],
    decoys: ["月", "山", "虫"],
  },
  {
    title: "静夜思",
    author: "李白",
    lines: ["床前明月光，", "疑是地上霜。", "举头望明月，", "低头思故乡。"],
    targets: ["床", "月", "光", "霜", "乡"],
    decoys: ["鹅", "花", "鸟"],
  },
  {
    title: "春晓",
    author: "孟浩然",
    lines: ["春眠不觉晓，", "处处闻啼鸟。", "夜来风雨声，", "花落知多少。"],
    targets: ["春", "眠", "鸟", "风", "花"],
    decoys: ["雪", "江", "火"],
  },
  {
    title: "登鹳雀楼",
    author: "王之涣",
    lines: ["白日依山尽，", "黄河入海流。", "欲穷千里目，", "更上一层楼。"],
    targets: ["日", "山", "河", "海", "楼"],
    decoys: ["鹅", "花", "夜"],
  },
  {
    title: "悯农",
    author: "李绅",
    lines: ["锄禾日当午，", "汗滴禾下土。", "谁知盘中餐，", "粒粒皆辛苦。"],
    targets: ["禾", "日", "汗", "土", "餐"],
    decoys: ["月", "鸟", "雪"],
  },
  {
    title: "江雪",
    author: "柳宗元",
    lines: ["千山鸟飞绝，", "万径人踪灭。", "孤舟蓑笠翁，", "独钓寒江雪。"],
    targets: ["鸟", "人", "舟", "江", "雪"],
    decoys: ["花", "春", "鹅"],
  },
  {
    title: "鹿柴",
    author: "王维",
    lines: ["空山不见人，", "但闻人语响。", "返景入深林，", "复照青苔上。"],
    targets: ["山", "人", "语", "林", "青"],
    decoys: ["水", "鹅", "火"],
  },
  {
    title: "画",
    author: "王维",
    lines: ["远看山有色，", "近听水无声。", "春去花还在，", "人来鸟不惊。"],
    targets: ["山", "水", "花", "鸟", "春"],
    decoys: ["月", "雪", "舟"],
  },
  {
    title: "小池",
    author: "杨万里",
    lines: ["泉眼无声惜细流，", "树阴照水爱晴柔。", "小荷才露尖尖角，", "早有蜻蜓立上头。"],
    targets: ["泉", "树", "水", "荷", "蜻"],
    decoys: ["鹅", "雪", "山"],
  },
  {
    title: "山村咏怀",
    author: "邵雍",
    lines: ["一去二三里，", "烟村四五家。", "亭台六七座，", "八九十枝花。"],
    targets: ["烟", "村", "亭", "家", "花"],
    decoys: ["月", "江", "鹅"],
  },
  {
    title: "古朗月行",
    author: "李白",
    lines: ["小时不识月，", "呼作白玉盘。", "又疑瑶台镜，", "飞在青云端。"],
    targets: ["月", "白", "盘", "镜", "云"],
    decoys: ["鹅", "花", "鸟"],
  },
  {
    title: "风",
    author: "李峤",
    lines: ["解落三秋叶，", "能开二月花。", "过江千尺浪，", "入竹万竿斜。"],
    targets: ["秋", "叶", "月", "花", "竹"],
    decoys: ["鹅", "雪", "床"],
  },
  {
    title: "寻隐者不遇",
    author: "贾岛",
    lines: ["松下问童子，", "言师采药去。", "只在此山中，", "云深不知处。"],
    targets: ["松", "童", "师", "山", "云"],
    decoys: ["鹅", "水", "日"],
  },
  {
    title: "绝句",
    author: "杜甫",
    lines: ["两个黄鹂鸣翠柳，", "一行白鹭上青天。", "窗含西岭千秋雪，", "门泊东吴万里船。"],
    targets: ["黄", "柳", "天", "雪", "船"],
    decoys: ["鹅", "月", "花"],
  },
  {
    title: "早发白帝城",
    author: "李白",
    lines: ["朝辞白帝彩云间，", "千里江陵一日还。", "两岸猿声啼不住，", "轻舟已过万重山。"],
    targets: ["云", "江", "舟", "山", "声"],
    decoys: ["花", "鹅", "雪"],
  },
  {
    title: "望庐山瀑布",
    author: "李白",
    lines: ["日照香炉生紫烟，", "遥看瀑布挂前川。", "飞流直下三千尺，", "疑是银河落九天。"],
    targets: ["日", "香", "烟", "川", "河"],
    decoys: ["鸟", "花", "鹅"],
  },
  {
    title: "赠汪伦",
    author: "李白",
    lines: ["李白乘舟将欲行，", "忽闻岸上踏歌声。", "桃花潭水深千尺，", "不及汪伦送我情。"],
    targets: ["白", "舟", "歌", "花", "水"],
    decoys: ["雪", "鸟", "月"],
  },
  {
    title: "游子吟",
    author: "孟郊",
    lines: ["慈母手中线，", "游子身上衣。", "临行密密缝，", "意恐迟迟归。", "谁言寸草心，", "报得三春晖。"],
    targets: ["母", "手", "线", "衣", "草"],
    decoys: ["鹅", "江", "雪"],
  },
  {
    title: "清明",
    author: "杜牧",
    lines: ["清明时节雨纷纷，", "路上行人欲断魂。", "借问酒家何处有，", "牧童遥指杏花村。"],
    targets: ["雨", "路", "人", "酒", "村"],
    decoys: ["月", "鹅", "雪"],
  },
  {
    title: "梅花",
    author: "王安石",
    lines: ["墙角数枝梅，", "凌寒独自开。", "遥知不是雪，", "为有暗香来。"],
    targets: ["墙", "梅", "寒", "雪", "香"],
    decoys: ["鸟", "水", "鹅"],
  },
];

const poemExplanations = {
  咏鹅: ["这首诗在看一只白鹅。", "白白的羽毛浮在绿水上，红红的脚掌轻轻划水。"],
  静夜思: ["诗人晚上看见明亮的月光。", "他低下头，想起了远方的家。"],
  春晓: ["春天早上醒来，听见到处都有小鸟叫。", "夜里刮风下雨，花可能落了不少。"],
  登鹳雀楼: ["诗人站在高楼上，看见太阳、山、黄河和大海。", "想看得更远，就要再上一层楼。"],
  悯农: ["农民在很热的中午辛苦种地。", "我们吃饭时，要记得粮食来得不容易。"],
  江雪: ["雪天里，山上没有鸟，路上没有人。", "只有一个老人在寒冷的江上钓鱼。"],
  鹿柴: ["山里很安静，看不见人。", "只听见有人说话的声音，阳光照进深深的树林。"],
  画: ["这首诗像在看一幅画。", "画里的山有颜色，水却没有声音，花和鸟一直在那里。"],
  小池: ["小小的泉水安静地流出来。", "荷叶刚露出尖尖角，蜻蜓已经站在上面了。"],
  山村咏怀: ["诗人一路走进小村子。", "他看见人家、亭台，还有很多花。"],
  古朗月行: ["小时候不认识月亮。", "孩子把圆圆的月亮想成白玉盘、明亮的镜子。"],
  风: ["风看不见，但能让叶子落下、花开放。", "风吹过江水和竹林，会留下很多变化。"],
  寻隐者不遇: ["诗人去找一位老师，可是老师采药去了。", "童子说老师就在山里，但云很深，不知道在哪里。"],
  绝句: ["诗里有黄鹂、白鹭、青天和雪山。", "窗外有远山，门前有小船，画面很美。"],
  早发白帝城: ["诗人早上从白帝城出发。", "小船走得很快，两岸的声音一路跟着他。"],
  望庐山瀑布: ["太阳照着香炉峰，远处瀑布像挂在山前。", "瀑布从高处飞下来，像银河落到天边。"],
  赠汪伦: ["李白坐船要离开，好朋友汪伦来送他。", "桃花潭水很深，也比不上朋友的情意。"],
  游子吟: ["妈妈一针一线给孩子缝衣服。", "这首诗在说妈妈的爱，很温暖。"],
  清明: ["清明时节常常下雨。", "路上的人有点难过，远处有杏花村。"],
  梅花: ["寒冷的时候，墙角的梅花独自开放。", "远远就知道那不是雪，因为有淡淡的香味。"],
};

const wordPool = ["日", "月", "山", "水", "火", "木", "云", "雨", "雪", "风", "花", "鸟", "虫", "天", "地", "人", "手", "口", "目", "耳", "大", "小", "上", "下", "白", "红", "青", "绿", "春", "夜"];

const poemPositions = [
  { x: 18, y: 24 },
  { x: 44, y: 18 },
  { x: 72, y: 26 },
  { x: 28, y: 48 },
  { x: 58, y: 47 },
  { x: 80, y: 55 },
  { x: 36, y: 72 },
  { x: 66, y: 74 },
];

const antonyms = [
  { a: "大", b: "小", action: "big-small" },
  { a: "多", b: "少", action: "big-small" },
  { a: "高", b: "矮", action: "tall-short" },
  { a: "长", b: "短", action: "tall-short" },
  { a: "胖", b: "瘦", action: "big-small" },
  { a: "上", b: "下", action: "up-down" },
  { a: "前", b: "后", action: "left-right" },
  { a: "左", b: "右", action: "left-right" },
  { a: "里", b: "外", action: "open-close" },
  { a: "开", b: "关", action: "open-close" },
  { a: "快", b: "慢", action: "fast-slow" },
  { a: "早", b: "晚", action: "fast-slow" },
  { a: "来", b: "去", action: "left-right" },
  { a: "进", b: "出", action: "left-right" },
  { a: "升", b: "降", action: "up-down" },
  { a: "坐", b: "站", action: "up-down" },
  { a: "笑", b: "哭", action: "happy-sad" },
  { a: "开心", b: "难过", action: "happy-sad" },
  { a: "热", b: "冷", action: "happy-sad" },
  { a: "亮", b: "暗", action: "open-close" },
  { a: "白", b: "黑", action: "open-close" },
  { a: "新", b: "旧", action: "happy-sad" },
  { a: "干", b: "湿", action: "happy-sad" },
  { a: "轻", b: "重", action: "big-small" },
  { a: "软", b: "硬", action: "big-small" },
  { a: "甜", b: "苦", action: "happy-sad" },
  { a: "香", b: "臭", action: "happy-sad" },
  { a: "好", b: "坏", action: "happy-sad" },
  { a: "真", b: "假", action: "open-close" },
  { a: "对", b: "错", action: "happy-sad" },
  { a: "直", b: "弯", action: "open-close" },
  { a: "粗", b: "细", action: "big-small" },
  { a: "厚", b: "薄", action: "big-small" },
  { a: "深", b: "浅", action: "up-down" },
  { a: "远", b: "近", action: "left-right" },
  { a: "东", b: "西", action: "left-right" },
  { a: "南", b: "北", action: "left-right" },
  { a: "天", b: "地", action: "up-down" },
  { a: "日", b: "夜", action: "open-close" },
  { a: "晴", b: "阴", action: "open-close" },
  { a: "动", b: "静", action: "fast-slow" },
  { a: "有", b: "无", action: "open-close" },
  { a: "满", b: "空", action: "big-small" },
  { a: "紧", b: "松", action: "open-close" },
  { a: "安全", b: "危险", action: "happy-sad" },
  { a: "勇敢", b: "害怕", action: "happy-sad" },
  { a: "安静", b: "吵闹", action: "fast-slow" },
  { a: "认真", b: "马虎", action: "happy-sad" },
  { a: "开始", b: "结束", action: "open-close" },
  { a: "喜欢", b: "讨厌", action: "happy-sad" },
  { a: "干净", b: "脏", action: "happy-sad" },
  { a: "整齐", b: "乱", action: "open-close" },
  { a: "聪明", b: "糊涂", action: "happy-sad" },
  { a: "勤劳", b: "懒惰", action: "fast-slow" },
  { a: "细心", b: "粗心", action: "happy-sad" },
  { a: "清楚", b: "模糊", action: "open-close" },
  { a: "简单", b: "复杂", action: "open-close" },
  { a: "容易", b: "困难", action: "happy-sad" },
  { a: "成功", b: "失败", action: "happy-sad" },
  { a: "入口", b: "出口", action: "left-right" },
  { a: "白天", b: "夜晚", action: "open-close" },
  { a: "夏天", b: "冬天", action: "happy-sad" },
  { a: "晴天", b: "雨天", action: "open-close" },
  { a: "加", b: "减", action: "big-small" },
  { a: "买", b: "卖", action: "left-right" },
  { a: "借", b: "还", action: "left-right" },
  { a: "推", b: "拉", action: "left-right" },
  { a: "抬", b: "放", action: "up-down" },
  { a: "穿", b: "脱", action: "open-close" },
  { a: "起床", b: "睡觉", action: "up-down" },
  { a: "饱", b: "饿", action: "happy-sad" },
  { a: "正", b: "反", action: "open-close" },
  { a: "正面", b: "反面", action: "open-close" },
  { a: "前进", b: "后退", action: "left-right" },
  { a: "上坡", b: "下坡", action: "up-down" },
  { a: "左转", b: "右转", action: "left-right" },
  { a: "高兴", b: "生气", action: "happy-sad" },
  { a: "温柔", b: "粗暴", action: "happy-sad" },
  { a: "明亮", b: "昏暗", action: "open-close" },
  { a: "温暖", b: "寒冷", action: "happy-sad" },
  { a: "里面", b: "外面", action: "open-close" },
  { a: "近处", b: "远处", action: "left-right" },
  { a: "快速", b: "缓慢", action: "fast-slow" },
  { a: "升起", b: "落下", action: "up-down" },
  { a: "合上", b: "打开", action: "open-close" },
  { a: "收", b: "放", action: "open-close" },
  { a: "问", b: "答", action: "open-close" },
  { a: "年轻", b: "年老", action: "tall-short" },
  { a: "坚强", b: "脆弱", action: "happy-sad" },
  { a: "胆大", b: "胆小", action: "big-small" },
  { a: "可爱", b: "可怕", action: "happy-sad" },
  { a: "熟悉", b: "陌生", action: "happy-sad" },
  { a: "内", b: "外", action: "open-close" },
  { a: "上升", b: "下降", action: "up-down" },
  { a: "关闭", b: "开启", action: "open-close" },
  { a: "出发", b: "到达", action: "left-right" },
  { a: "合", b: "分", action: "open-close" },
  { a: "强", b: "弱", action: "big-small" },
  { a: "胜", b: "败", action: "happy-sad" },
  { a: "先", b: "后", action: "left-right" },
];

const antonymWords = Array.from(new Set(antonyms.flatMap((item) => [item.a, item.b])));

const decorCatalog = [
  { type: "flower", icon: "✿", label: "团团花篱", rooms: ["spring"], cost: { stars: 1, flowers: 1 } },
  { type: "pinwheel", icon: "✣", label: "圆圆风车", rooms: ["spring"], cost: { stars: 2, flowers: 1 } },
  { type: "butterfly", icon: "♢", label: "春风彩蝶", rooms: ["spring"], cost: { stars: 2, flowers: 2 } },
  { type: "swing", icon: "◡", label: "小木秋千", rooms: ["spring"], cost: { stars: 3, flowers: 2 } },
  { type: "gate-charm", icon: "⌑", label: "红穗门饰", rooms: ["spring"], cost: { stars: 2, flowers: 1 } },
  { type: "pebble-path", icon: "○", label: "鹅卵小径", rooms: ["spring"], cost: { stars: 1, flowers: 2 } },
  { type: "potted-plum", icon: "❀", label: "圆盆梅枝", rooms: ["spring"], cost: { stars: 3, flowers: 3 } },
  { type: "tea-table", icon: "▱", label: "小茶桌", rooms: ["spring"], cost: { stars: 3, flowers: 1 } },

  { type: "brush-pot", icon: "▮", label: "毛笔小筒", rooms: ["study"], cost: { stars: 1, flowers: 1 } },
  { type: "seal-cube", icon: "■", label: "迷你印章", rooms: ["study"], cost: { stars: 2, flowers: 0 } },
  { type: "scroll", icon: "◧", label: "小卷轴", rooms: ["study"], cost: { stars: 2, flowers: 1 } },
  { type: "bamboo-slip", icon: "▤", label: "竹简架", rooms: ["study"], cost: { stars: 2, flowers: 2 } },
  { type: "inkstone", icon: "◒", label: "圆圆砚台", rooms: ["study"], cost: { stars: 1, flowers: 2 } },
  { type: "book-stack", icon: "▰", label: "叠叠书册", rooms: ["study"], cost: { stars: 3, flowers: 2 } },
  { type: "study-lamp", icon: "◉", label: "暖光书灯", rooms: ["study"], cost: { stars: 3, flowers: 1 } },
  { type: "window-curtain", icon: "⌒", label: "豆绿窗帘", rooms: ["study"], cost: { stars: 2, flowers: 3 } },

  { type: "moon", icon: "◐", label: "月亮灯笼", rooms: ["moon"], cost: { stars: 3, flowers: 2 } },
  { type: "star", icon: "✦", label: "星星挂灯", rooms: ["moon"], cost: { stars: 2, flowers: 0 } },
  { type: "cloud", icon: "☁", label: "软软祥云", rooms: ["moon"], cost: { stars: 1, flowers: 2 } },
  { type: "firefly", icon: "·", label: "萤火光点", rooms: ["moon"], cost: { stars: 1, flowers: 1 } },
  { type: "lantern", icon: "◍", label: "宫灯一盏", rooms: ["moon"], cost: { stars: 3, flowers: 1 } },
  { type: "bamboo-shadow", icon: "╱", label: "竹影屏风", rooms: ["moon"], cost: { stars: 2, flowers: 2 } },
  { type: "jade-rabbit-lamp", icon: "◌", label: "玉兔小灯", rooms: ["moon"], cost: { stars: 4, flowers: 2 } },
  { type: "cloud-step", icon: "〰", label: "云纹脚垫", rooms: ["moon"], cost: { stars: 2, flowers: 1 } },

  { type: "lotus", icon: "✾", label: "粉粉荷花", rooms: ["pond"], cost: { stars: 2, flowers: 2 } },
  { type: "lily-pad", icon: "●", label: "圆荷叶", rooms: ["pond"], cost: { stars: 1, flowers: 2 } },
  { type: "bridge", icon: "⌒", label: "小石拱桥", rooms: ["pond"], cost: { stars: 4, flowers: 2 } },
  { type: "water-ripple", icon: "≈", label: "水波圈圈", rooms: ["pond"], cost: { stars: 1, flowers: 1 } },
  { type: "pond-lamp", icon: "◉", label: "池边石灯", rooms: ["pond"], cost: { stars: 3, flowers: 1 } },
  { type: "reed", icon: "╲", label: "芦苇小丛", rooms: ["pond"], cost: { stars: 2, flowers: 2 } },
  { type: "dragonfly", icon: "✧", label: "小小蜻蜓", rooms: ["pond"], cost: { stars: 3, flowers: 2 } },
  { type: "fish-bubble", icon: "○", label: "泡泡水纹", rooms: ["pond"], cost: { stars: 2, flowers: 1 } },

  { type: "kite", icon: "◇", label: "彩纹纸鸢", rooms: ["spring", "moon"], cost: { stars: 4, flowers: 1 } },
  { type: "tree", icon: "♣", label: "圆叶小树", rooms: ["spring", "pond"], cost: { stars: 3, flowers: 2 } },
  { type: "book", icon: "▣", label: "唐诗小书", rooms: ["study", "moon"], cost: { stars: 2, flowers: 2 } },
  { type: "boy-water", icon: "童", label: "浇花书童", rooms: ["spring"], cost: { stars: 5, flowers: 3 } },
  { type: "girl-butterfly", icon: "童", label: "追蝶小仙", rooms: ["spring"], cost: { stars: 5, flowers: 3 } },
  { type: "boy-scroll", icon: "童", label: "读卷书童", rooms: ["study"], cost: { stars: 5, flowers: 2 } },
  { type: "girl-brush", icon: "童", label: "写字小仙", rooms: ["study"], cost: { stars: 5, flowers: 2 } },
  { type: "boy-moon", icon: "童", label: "提灯书童", rooms: ["moon"], cost: { stars: 5, flowers: 2 } },
  { type: "girl-lotus", icon: "童", label: "观荷小仙", rooms: ["pond"], cost: { stars: 5, flowers: 3 } },
];

const gardenRooms = [
  {
    id: "spring",
    label: "春日校园",
    hint: "挑些花篱、风车和小摆件，让院子热闹起来。",
    spots: [
      { x: 14, y: 74, size: "small" },
      { x: 28, y: 64, size: "medium" },
      { x: 43, y: 76, size: "small" },
      { x: 58, y: 62, size: "medium" },
      { x: 74, y: 74, size: "small" },
      { x: 86, y: 56, size: "small" },
      { x: 18, y: 42, size: "small" },
      { x: 36, y: 38, size: "large" },
      { x: 52, y: 44, size: "medium" },
      { x: 68, y: 36, size: "large" },
      { x: 82, y: 40, size: "small" },
      { x: 48, y: 25, size: "small" },
    ],
  },
  {
    id: "study",
    label: "识字书房",
    hint: "摆上笔墨、卷轴和小书灯，书房会更温暖。",
    spots: [
      { x: 17, y: 70, size: "medium" },
      { x: 31, y: 61, size: "small" },
      { x: 47, y: 68, size: "large" },
      { x: 64, y: 59, size: "medium" },
      { x: 80, y: 68, size: "small" },
      { x: 20, y: 42, size: "small" },
      { x: 36, y: 34, size: "medium" },
      { x: 52, y: 39, size: "small" },
      { x: 69, y: 32, size: "medium" },
      { x: 83, y: 43, size: "small" },
    ],
  },
  {
    id: "moon",
    label: "月光庭院",
    hint: "挂上月灯、星灯和祥云，夜晚会亮起来。",
    spots: [
      { x: 13, y: 67, size: "small" },
      { x: 27, y: 76, size: "medium" },
      { x: 43, y: 66, size: "small" },
      { x: 59, y: 76, size: "medium" },
      { x: 76, y: 65, size: "small" },
      { x: 88, y: 52, size: "small" },
      { x: 18, y: 35, size: "medium" },
      { x: 36, y: 28, size: "small" },
      { x: 54, y: 34, size: "large" },
      { x: 72, y: 27, size: "small" },
      { x: 84, y: 37, size: "medium" },
    ],
  },
  {
    id: "pond",
    label: "小荷池",
    hint: "添些荷叶、水纹和小石灯，让池边更有生气。",
    spots: [
      { x: 14, y: 64, size: "small" },
      { x: 28, y: 73, size: "medium" },
      { x: 44, y: 62, size: "large" },
      { x: 60, y: 72, size: "medium" },
      { x: 77, y: 63, size: "small" },
      { x: 88, y: 78, size: "small" },
      { x: 20, y: 42, size: "medium" },
      { x: 39, y: 35, size: "small" },
      { x: 56, y: 41, size: "medium" },
      { x: 73, y: 34, size: "small" },
      { x: 84, y: 45, size: "small" },
    ],
  },
];
